package com.uca.statistic.vo;

// Generated 2015-6-4 16:56:21 by Hibernate Tools 3.4.0.CR1

/**
 * UcaArchivesCatalog generated by hbm2java
 */
public class UcaOrgArchivesStatisticVo implements java.io.Serializable {

    /**
	 * 
	 */
    private static final long serialVersionUID = 1L;
    private int id;
    private int yv;
    private String ona;
    private String un;
    private int uid;
    private String up;
    private String ct;
    private int c1;
    private int c2;
    private int c3;
    private int c4;
    private int c5;
    private int c6;
    private int c7;
    private int c8;
    private int c9;
    private int c10;
    private int c11;
    private int c12;
    private int c13;
    private int c14;
    private int c15;
    private int c16;
    private int c17;
    private int c18;
    private int c19;
    private int c20;
    private int c21;
    private int c22;
    private int c23;
    private int c24;
    private int c25;
    private int c26;
    private int c27;
    private int c28;
    private int c29;// 第29行=46+55
    private int c30;
    private int c31;// 第31行=47+56
    private int c32;
    private int c33;
    private int c34;
    private int c35;
    private int c36;
    private int c37;
    private int c381;
    private int c382;
    private int c383;
    private int c39;
    private int c40;
    private int c41;
    private int c42;
    private int c43;
    private int c44;
    private int c45;
    private int c46;// 第46行=49+51+53
    private int c47;// 第47行=48+50+52+54
    private int c48;
    private int c49;
    private int c50;
    private int c51;
    private int c52;
    private int c53;
    private int c54;
    private int c55;
    private int c56;
    private int c57;
    private int c58;
    private int c59;
    private int c60;
    private int c61;
    private int c62;
    private int c63;
    private int c64;
    private int c65;
    private int c66;
    private int c67;
    private int c68;
    private int c69;
    private int c70;// 第70行=72+74=76+78
    private int c71;// 第71行=73+75=77+79
    private int c72;
    private int c73;
    private int c74;
    private int c75;
    private int c76;
    private int c77;
    private int c78;
    private int c79;
    private int c80;
    private int c81;
    private int c82;// 82≥83
    private int c83;
    private int c84;
    private int c85;
    private int c86;
    private int c87;
    private int c88;
    private int c89;// 89≥90＋91＋92＋93
    private int c90;
    private int c91;
    private int c92;
    private int c93;
    private int c94;
    private int c95;
    private int c96;
    private int c97;
    private int c98;
    private int c99;
    private int c100;
    private int c101;
    private int c102;
    private int c103;
    private int c104;
    private int c105;
    private int c106;
    private int c107;
    private int c108;
    private int c109;
    private int c110;
    private int c111;
    private int c112;
    private int c113;
    private int c114;
    private int c115;
    private int c116;
    private int c117;
    private int c118;
    private int c119;
    private int c120;
    private int c121;
    private int c122;
    private int c123;

    private String cun;

    public String getCun() {
        return cun;
    }

    public void setCun(String cun) {
        this.cun = cun;
    }

    public int getYv() {
        return yv;
    }

    public void setYv(int yv) {
        this.yv = yv;
    }

    public String getOna() {
        return ona;
    }

    public void setOna(String ona) {
        this.ona = ona;
    }

    public String getUn() {
        return un;
    }

    public void setUn(String un) {
        this.un = un;
    }

    public int getUid() {
        return uid;
    }

    public void setUid(int uid) {
        this.uid = uid;
    }

    public String getUp() {
        return up;
    }

    public void setUp(String up) {
        this.up = up;
    }

    public String getCt() {
        return ct;
    }

    public void setCt(String ct) {
        this.ct = ct;
    }

    public int getC381() {
        return c381;
    }

    public void setC381(int c381) {
        this.c381 = c381;
    }

    public int getC382() {
        return c382;
    }

    public void setC382(int c382) {
        this.c382 = c382;
    }

    public int getC383() {
        return c383;
    }

    public void setC383(int c383) {
        this.c383 = c383;
    }

    public UcaOrgArchivesStatisticVo() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getC1() {
        return c1;
    }

    public void setC1(int c1) {
        this.c1 = c1;
    }

    public int getC2() {
        return c2;
    }

    public void setC2(int c2) {
        this.c2 = c2;
    }

    public int getC3() {
        return c3;
    }

    public void setC3(int c3) {
        this.c3 = c3;
    }

    public int getC4() {
        return c4;
    }

    public void setC4(int c4) {
        this.c4 = c4;
    }

    public int getC5() {
        return c5;
    }

    public void setC5(int c5) {
        this.c5 = c5;
    }

    public int getC6() {
        return c6;
    }

    public void setC6(int c6) {
        this.c6 = c6;
    }

    public int getC7() {
        return c7;
    }

    public void setC7(int c7) {
        this.c7 = c7;
    }

    public int getC8() {
        return c8;
    }

    public void setC8(int c8) {
        this.c8 = c8;
    }

    public int getC9() {
        return c9;
    }

    public void setC9(int c9) {
        this.c9 = c9;
    }

    public int getC10() {
        return c10;
    }

    public void setC10(int c10) {
        this.c10 = c10;
    }

    public int getC11() {
        return c11;
    }

    public void setC11(int c11) {
        this.c11 = c11;
    }

    public int getC12() {
        return c12;
    }

    public void setC12(int c12) {
        this.c12 = c12;
    }

    public int getC13() {
        return c13;
    }

    public void setC13(int c13) {
        this.c13 = c13;
    }

    public int getC14() {
        return c14;
    }

    public void setC14(int c14) {
        this.c14 = c14;
    }

    public int getC15() {
        return c15;
    }

    public void setC15(int c15) {
        this.c15 = c15;
    }

    public int getC16() {
        return c16;
    }

    public void setC16(int c16) {
        this.c16 = c16;
    }

    public int getC17() {
        return c17;
    }

    public void setC17(int c17) {
        this.c17 = c17;
    }

    public int getC18() {
        return c18;
    }

    public void setC18(int c18) {
        this.c18 = c18;
    }

    public int getC19() {
        return c19;
    }

    public void setC19(int c19) {
        this.c19 = c19;
    }

    public int getC20() {
        return c20;
    }

    public void setC20(int c20) {
        this.c20 = c20;
    }

    public int getC21() {
        return c21;
    }

    public void setC21(int c21) {
        this.c21 = c21;
    }

    public int getC22() {
        return c22;
    }

    public void setC22(int c22) {
        this.c22 = c22;
    }

    public int getC23() {
        return c23;
    }

    public void setC23(int c23) {
        this.c23 = c23;
    }

    public int getC24() {
        return c24;
    }

    public void setC24(int c24) {
        this.c24 = c24;
    }

    public int getC25() {
        return c25;
    }

    public void setC25(int c25) {
        this.c25 = c25;
    }

    public int getC26() {
        return c26;
    }

    public void setC26(int c26) {
        this.c26 = c26;
    }

    public int getC27() {
        return c27;
    }

    public void setC27(int c27) {
        this.c27 = c27;
    }

    public int getC28() {
        return c28;
    }

    public void setC28(int c28) {
        this.c28 = c28;
    }

    public int getC29() {
        return c29;
    }

    public void setC29(int c29) {
        this.c29 = c29;
    }

    public int getC30() {
        return c30;
    }

    public void setC30(int c30) {
        this.c30 = c30;
    }

    public int getC31() {
        return c31;
    }

    public void setC31(int c31) {
        this.c31 = c31;
    }

    public int getC32() {
        return c32;
    }

    public void setC32(int c32) {
        this.c32 = c32;
    }

    public int getC33() {
        return c33;
    }

    public void setC33(int c33) {
        this.c33 = c33;
    }

    public int getC34() {
        return c34;
    }

    public void setC34(int c34) {
        this.c34 = c34;
    }

    public int getC35() {
        return c35;
    }

    public void setC35(int c35) {
        this.c35 = c35;
    }

    public int getC36() {
        return c36;
    }

    public void setC36(int c36) {
        this.c36 = c36;
    }

    public int getC37() {
        return c37;
    }

    public void setC37(int c37) {
        this.c37 = c37;
    }

    public int getC39() {
        return c39;
    }

    public void setC39(int c39) {
        this.c39 = c39;
    }

    public int getC40() {
        return c40;
    }

    public void setC40(int c40) {
        this.c40 = c40;
    }

    public int getC41() {
        return c41;
    }

    public void setC41(int c41) {
        this.c41 = c41;
    }

    public int getC42() {
        return c42;
    }

    public void setC42(int c42) {
        this.c42 = c42;
    }

    public int getC43() {
        return c43;
    }

    public void setC43(int c43) {
        this.c43 = c43;
    }

    public int getC44() {
        return c44;
    }

    public void setC44(int c44) {
        this.c44 = c44;
    }

    public int getC45() {
        return c45;
    }

    public void setC45(int c45) {
        this.c45 = c45;
    }

    public int getC46() {
        return c46;
    }

    public void setC46(int c46) {
        this.c46 = c46;
    }

    public int getC47() {
        return c47;
    }

    public void setC47(int c47) {
        this.c47 = c47;
    }

    public int getC48() {
        return c48;
    }

    public void setC48(int c48) {
        this.c48 = c48;
    }

    public int getC49() {
        return c49;
    }

    public void setC49(int c49) {
        this.c49 = c49;
    }

    public int getC50() {
        return c50;
    }

    public void setC50(int c50) {
        this.c50 = c50;
    }

    public int getC51() {
        return c51;
    }

    public void setC51(int c51) {
        this.c51 = c51;
    }

    public int getC52() {
        return c52;
    }

    public void setC52(int c52) {
        this.c52 = c52;
    }

    public int getC53() {
        return c53;
    }

    public void setC53(int c53) {
        this.c53 = c53;
    }

    public int getC54() {
        return c54;
    }

    public void setC54(int c54) {
        this.c54 = c54;
    }

    public int getC55() {
        return c55;
    }

    public void setC55(int c55) {
        this.c55 = c55;
    }

    public int getC56() {
        return c56;
    }

    public void setC56(int c56) {
        this.c56 = c56;
    }

    public int getC57() {
        return c57;
    }

    public void setC57(int c57) {
        this.c57 = c57;
    }

    public int getC58() {
        return c58;
    }

    public void setC58(int c58) {
        this.c58 = c58;
    }

    public int getC59() {
        return c59;
    }

    public void setC59(int c59) {
        this.c59 = c59;
    }

    public int getC60() {
        return c60;
    }

    public void setC60(int c60) {
        this.c60 = c60;
    }

    public int getC61() {
        return c61;
    }

    public void setC61(int c61) {
        this.c61 = c61;
    }

    public int getC62() {
        return c62;
    }

    public void setC62(int c62) {
        this.c62 = c62;
    }

    public int getC63() {
        return c63;
    }

    public void setC63(int c63) {
        this.c63 = c63;
    }

    public int getC64() {
        return c64;
    }

    public void setC64(int c64) {
        this.c64 = c64;
    }

    public int getC65() {
        return c65;
    }

    public void setC65(int c65) {
        this.c65 = c65;
    }

    public int getC66() {
        return c66;
    }

    public void setC66(int c66) {
        this.c66 = c66;
    }

    public int getC67() {
        return c67;
    }

    public void setC67(int c67) {
        this.c67 = c67;
    }

    public int getC68() {
        return c68;
    }

    public void setC68(int c68) {
        this.c68 = c68;
    }

    public int getC69() {
        return c69;
    }

    public void setC69(int c69) {
        this.c69 = c69;
    }

    public int getC70() {
        return c70;
    }

    public void setC70(int c70) {
        this.c70 = c70;
    }

    public int getC71() {
        return c71;
    }

    public void setC71(int c71) {
        this.c71 = c71;
    }

    public int getC72() {
        return c72;
    }

    public void setC72(int c72) {
        this.c72 = c72;
    }

    public int getC73() {
        return c73;
    }

    public void setC73(int c73) {
        this.c73 = c73;
    }

    public int getC74() {
        return c74;
    }

    public void setC74(int c74) {
        this.c74 = c74;
    }

    public int getC75() {
        return c75;
    }

    public void setC75(int c75) {
        this.c75 = c75;
    }

    public int getC76() {
        return c76;
    }

    public void setC76(int c76) {
        this.c76 = c76;
    }

    public int getC77() {
        return c77;
    }

    public void setC77(int c77) {
        this.c77 = c77;
    }

    public int getC78() {
        return c78;
    }

    public void setC78(int c78) {
        this.c78 = c78;
    }

    public int getC79() {
        return c79;
    }

    public void setC79(int c79) {
        this.c79 = c79;
    }

    public int getC80() {
        return c80;
    }

    public void setC80(int c80) {
        this.c80 = c80;
    }

    public int getC81() {
        return c81;
    }

    public void setC81(int c81) {
        this.c81 = c81;
    }

    public int getC82() {
        return c82;
    }

    public void setC82(int c82) {
        this.c82 = c82;
    }

    public int getC83() {
        return c83;
    }

    public void setC83(int c83) {
        this.c83 = c83;
    }

    public int getC84() {
        return c84;
    }

    public void setC84(int c84) {
        this.c84 = c84;
    }

    public int getC85() {
        return c85;
    }

    public void setC85(int c85) {
        this.c85 = c85;
    }

    public int getC86() {
        return c86;
    }

    public void setC86(int c86) {
        this.c86 = c86;
    }

    public int getC87() {
        return c87;
    }

    public void setC87(int c87) {
        this.c87 = c87;
    }

    public int getC88() {
        return c88;
    }

    public void setC88(int c88) {
        this.c88 = c88;
    }

    public int getC89() {
        return c89;
    }

    public void setC89(int c89) {
        this.c89 = c89;
    }

    public int getC90() {
        return c90;
    }

    public void setC90(int c90) {
        this.c90 = c90;
    }

    public int getC91() {
        return c91;
    }

    public void setC91(int c91) {
        this.c91 = c91;
    }

    public int getC92() {
        return c92;
    }

    public void setC92(int c92) {
        this.c92 = c92;
    }

    public int getC93() {
        return c93;
    }

    public void setC93(int c93) {
        this.c93 = c93;
    }

    public int getC94() {
        return c94;
    }

    public void setC94(int c94) {
        this.c94 = c94;
    }

    public int getC95() {
        return c95;
    }

    public void setC95(int c95) {
        this.c95 = c95;
    }

    public int getC96() {
        return c96;
    }

    public void setC96(int c96) {
        this.c96 = c96;
    }

    public int getC97() {
        return c97;
    }

    public void setC97(int c97) {
        this.c97 = c97;
    }

    public int getC98() {
        return c98;
    }

    public void setC98(int c98) {
        this.c98 = c98;
    }

    public int getC99() {
        return c99;
    }

    public void setC99(int c99) {
        this.c99 = c99;
    }

    public int getC100() {
        return c100;
    }

    public void setC100(int c100) {
        this.c100 = c100;
    }

    public int getC101() {
        return c101;
    }

    public void setC101(int c101) {
        this.c101 = c101;
    }

    public int getC102() {
        return c102;
    }

    public void setC102(int c102) {
        this.c102 = c102;
    }

    public int getC103() {
        return c103;
    }

    public void setC103(int c103) {
        this.c103 = c103;
    }

    public int getC104() {
        return c104;
    }

    public void setC104(int c104) {
        this.c104 = c104;
    }

    public int getC105() {
        return c105;
    }

    public void setC105(int c105) {
        this.c105 = c105;
    }

    public int getC106() {
        return c106;
    }

    public void setC106(int c106) {
        this.c106 = c106;
    }

    public int getC107() {
        return c107;
    }

    public void setC107(int c107) {
        this.c107 = c107;
    }

    public int getC108() {
        return c108;
    }

    public void setC108(int c108) {
        this.c108 = c108;
    }

    public int getC109() {
        return c109;
    }

    public void setC109(int c109) {
        this.c109 = c109;
    }

    public int getC110() {
        return c110;
    }

    public void setC110(int c110) {
        this.c110 = c110;
    }

    public int getC111() {
        return c111;
    }

    public void setC111(int c111) {
        this.c111 = c111;
    }

    public int getC112() {
        return c112;
    }

    public void setC112(int c112) {
        this.c112 = c112;
    }

    public int getC113() {
        return c113;
    }

    public void setC113(int c113) {
        this.c113 = c113;
    }

    public int getC114() {
        return c114;
    }

    public void setC114(int c114) {
        this.c114 = c114;
    }

    public int getC115() {
        return c115;
    }

    public void setC115(int c115) {
        this.c115 = c115;
    }

    public int getC116() {
        return c116;
    }

    public void setC116(int c116) {
        this.c116 = c116;
    }

    public int getC117() {
        return c117;
    }

    public void setC117(int c117) {
        this.c117 = c117;
    }

    public int getC118() {
        return c118;
    }

    public void setC118(int c118) {
        this.c118 = c118;
    }

    public int getC119() {
        return c119;
    }

    public void setC119(int c119) {
        this.c119 = c119;
    }

    public int getC120() {
        return c120;
    }

    public void setC120(int c120) {
        this.c120 = c120;
    }

    public int getC121() {
        return c121;
    }

    public void setC121(int c121) {
        this.c121 = c121;
    }

    public int getC122() {
        return c122;
    }

    public void setC122(int c122) {
        this.c122 = c122;
    }

    public int getC123() {
        return c123;
    }

    public void setC123(int c123) {
        this.c123 = c123;
    }

}
