package com.uca.statistic.pojos;

// Generated 2015-6-4 16:56:21 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UcaArchivesCatalog generated by hbm2java
 */
public class UcaOrgArchivesStatistic implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private int yearValue;
//	private int orgId;
//	private int userId;
	private String orgName;
	private String userName;
	private int createUserId;
	private String createUserPhone;
	private Date createTime;
	private int code_1;
	private int code_2;
	private int code_3;
	private int code_4;
	private int code_5;
	private int code_6;
	private int code_7;
	private int code_8;
	private int code_9;
	private int code_10;
	private int code_11;
	private int code_12;
	private int code_13;
	private int code_14;
	private int code_15;
	private int code_16;
	private int code_17;
	private int code_18;
	private int code_19;
	private int code_20;
	private int code_21;
	private int code_22;
	private int code_23;
	private int code_24;
	private int code_25;
	private int code_26;
	private int code_27;
	private int code_28;
	private int code_29;//第29行=46+55
	private int code_30;
	private int code_31;//第31行=47+56
	private int code_32;
	private int code_33;
	private int code_34;
	private int code_35;
	private int code_36;
	private int code_37;
	private int code_38_1;
	private int code_38_2;
	private int code_38_3;
	private int code_39;
	private int code_40;
	private int code_41;
	private int code_42;
	private int code_43;
	private int code_44;
	private int code_45;
	private int code_46;//第46行=49+51+53
	private int code_47;//第47行=48+50+52+54
	private int code_48;
	private int code_49;
	private int code_50;
	private int code_51;
	private int code_52;
	private int code_53;
	private int code_54;
	private int code_55;
	private int code_56;
	private int code_57;
	private int code_58;
	private int code_59;
	private int code_60;
	private int code_61;
	private int code_62;
	private int code_63;
	private int code_64;
	private int code_65;
	private int code_66;
	private int code_67;
	private int code_68;
	private int code_69;
	private int code_70;//第70行=72+74=76+78
	private int code_71;//第71行=73+75=77+79
	private int code_72;
	private int code_73;
	private int code_74;
	private int code_75;
	private int code_76;
	private int code_77;
	private int code_78;
	private int code_79;
	private int code_80;
	private int code_81;
	private int code_82;//82≥83
	private int code_83;
	private int code_84;
	private int code_85;
	private int code_86;
	private int code_87;
	private int code_88;
	private int code_89;//89≥90＋91＋92＋93
	private int code_90;
	private int code_91;
	private int code_92;
	private int code_93;
	private int code_94;
	private int code_95;
	private int code_96;
	private int code_97;
	private int code_98;
	private int code_99;
	private int code_100;
	private int code_101;
	private int code_102;
	private int code_103;
	private int code_104;
	private int code_105;
	private int code_106;
	private int code_107;
	private int code_108;
	private int code_109;
	private int code_110;
	private int code_111;
	private int code_112;
	private int code_113;
	private int code_114;
	private int code_115;
	private int code_116;
	private int code_117;
	private int code_118;
	private int code_119;
	private int code_120;
	private int code_121;
	private int code_122;
	private int code_123;
	
	private String createUserName;
	
	public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getCreateUserName() {
		return createUserName;
	}

	public void setCreateUserName(String createUserName) {
		this.createUserName = createUserName;
	}

	public UcaOrgArchivesStatistic() {
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getYearValue() {
		return yearValue;
	}

	public void setYearValue(int yearValue) {
		this.yearValue = yearValue;
	}

//	public int getOrgId() {
//		return orgId;
//	}
//
//	public void setOrgId(int orgId) {
//		this.orgId = orgId;
//	}
//
//	public int getUserId() {
//		return userId;
//	}
//
//	public void setUserId(int userId) {
//		this.userId = userId;
//	}

	public int getCreateUserId() {
		return createUserId;
	}

	public void setCreateUserId(int createUserId) {
		this.createUserId = createUserId;
	}

	public String getCreateUserPhone() {
		return createUserPhone;
	}

	public void setCreateUserPhone(String createUserPhone) {
		this.createUserPhone = createUserPhone;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public int getCode_1() {
		return code_1;
	}

	public void setCode_1(int code_1) {
		this.code_1 = code_1;
	}

	public int getCode_2() {
		return code_2;
	}

	public void setCode_2(int code_2) {
		this.code_2 = code_2;
	}

	public int getCode_3() {
		return code_3;
	}

	public void setCode_3(int code_3) {
		this.code_3 = code_3;
	}

	public int getCode_4() {
		return code_4;
	}

	public void setCode_4(int code_4) {
		this.code_4 = code_4;
	}

	public int getCode_5() {
		return code_5;
	}

	public void setCode_5(int code_5) {
		this.code_5 = code_5;
	}

	public int getCode_6() {
		return code_6;
	}

	public void setCode_6(int code_6) {
		this.code_6 = code_6;
	}

	public int getCode_7() {
		return code_7;
	}

	public void setCode_7(int code_7) {
		this.code_7 = code_7;
	}

	public int getCode_8() {
		return code_8;
	}

	public void setCode_8(int code_8) {
		this.code_8 = code_8;
	}

	public int getCode_9() {
		return code_9;
	}

	public void setCode_9(int code_9) {
		this.code_9 = code_9;
	}

	public int getCode_10() {
		return code_10;
	}

	public void setCode_10(int code_10) {
		this.code_10 = code_10;
	}

	public int getCode_11() {
		return code_11;
	}

	public void setCode_11(int code_11) {
		this.code_11 = code_11;
	}

	public int getCode_12() {
		return code_12;
	}

	public void setCode_12(int code_12) {
		this.code_12 = code_12;
	}

	public int getCode_13() {
		return code_13;
	}

	public void setCode_13(int code_13) {
		this.code_13 = code_13;
	}

	public int getCode_14() {
		return code_14;
	}

	public void setCode_14(int code_14) {
		this.code_14 = code_14;
	}

	public int getCode_15() {
		return code_15;
	}

	public void setCode_15(int code_15) {
		this.code_15 = code_15;
	}

	public int getCode_16() {
		return code_16;
	}

	public void setCode_16(int code_16) {
		this.code_16 = code_16;
	}

	public int getCode_17() {
		return code_17;
	}

	public void setCode_17(int code_17) {
		this.code_17 = code_17;
	}

	public int getCode_18() {
		return code_18;
	}

	public void setCode_18(int code_18) {
		this.code_18 = code_18;
	}

	public int getCode_19() {
		return code_19;
	}

	public void setCode_19(int code_19) {
		this.code_19 = code_19;
	}

	public int getCode_20() {
		return code_20;
	}

	public void setCode_20(int code_20) {
		this.code_20 = code_20;
	}

	public int getCode_21() {
		return code_21;
	}

	public void setCode_21(int code_21) {
		this.code_21 = code_21;
	}

	public int getCode_22() {
		return code_22;
	}

	public void setCode_22(int code_22) {
		this.code_22 = code_22;
	}

	public int getCode_23() {
		return code_23;
	}

	public void setCode_23(int code_23) {
		this.code_23 = code_23;
	}

	public int getCode_24() {
		return code_24;
	}

	public void setCode_24(int code_24) {
		this.code_24 = code_24;
	}

	public int getCode_25() {
		return code_25;
	}

	public void setCode_25(int code_25) {
		this.code_25 = code_25;
	}

	public int getCode_26() {
		return code_26;
	}

	public void setCode_26(int code_26) {
		this.code_26 = code_26;
	}

	public int getCode_27() {
		return code_27;
	}

	public void setCode_27(int code_27) {
		this.code_27 = code_27;
	}

	public int getCode_28() {
		return code_28;
	}

	public void setCode_28(int code_28) {
		this.code_28 = code_28;
	}

	public int getCode_29() {
		return code_29;
	}

	public void setCode_29(int code_29) {
		this.code_29 = code_29;
	}

	public int getCode_30() {
		return code_30;
	}

	public void setCode_30(int code_30) {
		this.code_30 = code_30;
	}

	public int getCode_31() {
		return code_31;
	}

	public void setCode_31(int code_31) {
		this.code_31 = code_31;
	}

	public int getCode_32() {
		return code_32;
	}

	public void setCode_32(int code_32) {
		this.code_32 = code_32;
	}

	public int getCode_33() {
		return code_33;
	}

	public void setCode_33(int code_33) {
		this.code_33 = code_33;
	}

	public int getCode_34() {
		return code_34;
	}

	public void setCode_34(int code_34) {
		this.code_34 = code_34;
	}

	public int getCode_35() {
		return code_35;
	}

	public void setCode_35(int code_35) {
		this.code_35 = code_35;
	}

	public int getCode_36() {
		return code_36;
	}

	public void setCode_36(int code_36) {
		this.code_36 = code_36;
	}

	public int getCode_37() {
		return code_37;
	}

	public void setCode_37(int code_37) {
		this.code_37 = code_37;
	}

	public int getCode_38_1() {
		return code_38_1;
	}

	public void setCode_38_1(int code_38_1) {
		this.code_38_1 = code_38_1;
	}

	public int getCode_38_2() {
		return code_38_2;
	}

	public void setCode_38_2(int code_38_2) {
		this.code_38_2 = code_38_2;
	}

	public int getCode_38_3() {
		return code_38_3;
	}

	public void setCode_38_3(int code_38_3) {
		this.code_38_3 = code_38_3;
	}

	public int getCode_39() {
		return code_39;
	}

	public void setCode_39(int code_39) {
		this.code_39 = code_39;
	}

	public int getCode_40() {
		return code_40;
	}

	public void setCode_40(int code_40) {
		this.code_40 = code_40;
	}

	public int getCode_41() {
		return code_41;
	}

	public void setCode_41(int code_41) {
		this.code_41 = code_41;
	}

	public int getCode_42() {
		return code_42;
	}

	public void setCode_42(int code_42) {
		this.code_42 = code_42;
	}

	public int getCode_43() {
		return code_43;
	}

	public void setCode_43(int code_43) {
		this.code_43 = code_43;
	}

	public int getCode_44() {
		return code_44;
	}

	public void setCode_44(int code_44) {
		this.code_44 = code_44;
	}

	public int getCode_45() {
		return code_45;
	}

	public void setCode_45(int code_45) {
		this.code_45 = code_45;
	}

	public int getCode_46() {
		return code_46;
	}

	public void setCode_46(int code_46) {
		this.code_46 = code_46;
	}

	public int getCode_47() {
		return code_47;
	}

	public void setCode_47(int code_47) {
		this.code_47 = code_47;
	}

	public int getCode_48() {
		return code_48;
	}

	public void setCode_48(int code_48) {
		this.code_48 = code_48;
	}

	public int getCode_49() {
		return code_49;
	}

	public void setCode_49(int code_49) {
		this.code_49 = code_49;
	}

	public int getCode_50() {
		return code_50;
	}

	public void setCode_50(int code_50) {
		this.code_50 = code_50;
	}

	public int getCode_51() {
		return code_51;
	}

	public void setCode_51(int code_51) {
		this.code_51 = code_51;
	}

	public int getCode_52() {
		return code_52;
	}

	public void setCode_52(int code_52) {
		this.code_52 = code_52;
	}

	public int getCode_53() {
		return code_53;
	}

	public void setCode_53(int code_53) {
		this.code_53 = code_53;
	}

	public int getCode_54() {
		return code_54;
	}

	public void setCode_54(int code_54) {
		this.code_54 = code_54;
	}

	public int getCode_55() {
		return code_55;
	}

	public void setCode_55(int code_55) {
		this.code_55 = code_55;
	}

	public int getCode_56() {
		return code_56;
	}

	public void setCode_56(int code_56) {
		this.code_56 = code_56;
	}

	public int getCode_57() {
		return code_57;
	}

	public void setCode_57(int code_57) {
		this.code_57 = code_57;
	}

	public int getCode_58() {
		return code_58;
	}

	public void setCode_58(int code_58) {
		this.code_58 = code_58;
	}

	public int getCode_59() {
		return code_59;
	}

	public void setCode_59(int code_59) {
		this.code_59 = code_59;
	}

	public int getCode_60() {
		return code_60;
	}

	public void setCode_60(int code_60) {
		this.code_60 = code_60;
	}

	public int getCode_61() {
		return code_61;
	}

	public void setCode_61(int code_61) {
		this.code_61 = code_61;
	}

	public int getCode_62() {
		return code_62;
	}

	public void setCode_62(int code_62) {
		this.code_62 = code_62;
	}

	public int getCode_63() {
		return code_63;
	}

	public void setCode_63(int code_63) {
		this.code_63 = code_63;
	}

	public int getCode_64() {
		return code_64;
	}

	public void setCode_64(int code_64) {
		this.code_64 = code_64;
	}

	public int getCode_65() {
		return code_65;
	}

	public void setCode_65(int code_65) {
		this.code_65 = code_65;
	}

	public int getCode_66() {
		return code_66;
	}

	public void setCode_66(int code_66) {
		this.code_66 = code_66;
	}

	public int getCode_67() {
		return code_67;
	}

	public void setCode_67(int code_67) {
		this.code_67 = code_67;
	}

	public int getCode_68() {
		return code_68;
	}

	public void setCode_68(int code_68) {
		this.code_68 = code_68;
	}

	public int getCode_69() {
		return code_69;
	}

	public void setCode_69(int code_69) {
		this.code_69 = code_69;
	}

	public int getCode_70() {
		return code_70;
	}

	public void setCode_70(int code_70) {
		this.code_70 = code_70;
	}

	public int getCode_71() {
		return code_71;
	}

	public void setCode_71(int code_71) {
		this.code_71 = code_71;
	}

	public int getCode_72() {
		return code_72;
	}

	public void setCode_72(int code_72) {
		this.code_72 = code_72;
	}

	public int getCode_73() {
		return code_73;
	}

	public void setCode_73(int code_73) {
		this.code_73 = code_73;
	}

	public int getCode_74() {
		return code_74;
	}

	public void setCode_74(int code_74) {
		this.code_74 = code_74;
	}

	public int getCode_75() {
		return code_75;
	}

	public void setCode_75(int code_75) {
		this.code_75 = code_75;
	}

	public int getCode_76() {
		return code_76;
	}

	public void setCode_76(int code_76) {
		this.code_76 = code_76;
	}

	public int getCode_77() {
		return code_77;
	}

	public void setCode_77(int code_77) {
		this.code_77 = code_77;
	}

	public int getCode_78() {
		return code_78;
	}

	public void setCode_78(int code_78) {
		this.code_78 = code_78;
	}

	public int getCode_79() {
		return code_79;
	}

	public void setCode_79(int code_79) {
		this.code_79 = code_79;
	}

	public int getCode_80() {
		return code_80;
	}

	public void setCode_80(int code_80) {
		this.code_80 = code_80;
	}

	public int getCode_81() {
		return code_81;
	}

	public void setCode_81(int code_81) {
		this.code_81 = code_81;
	}

	public int getCode_82() {
		return code_82;
	}

	public void setCode_82(int code_82) {
		this.code_82 = code_82;
	}

	public int getCode_83() {
		return code_83;
	}

	public void setCode_83(int code_83) {
		this.code_83 = code_83;
	}

	public int getCode_84() {
		return code_84;
	}

	public void setCode_84(int code_84) {
		this.code_84 = code_84;
	}

	public int getCode_85() {
		return code_85;
	}

	public void setCode_85(int code_85) {
		this.code_85 = code_85;
	}

	public int getCode_86() {
		return code_86;
	}

	public void setCode_86(int code_86) {
		this.code_86 = code_86;
	}

	public int getCode_87() {
		return code_87;
	}

	public void setCode_87(int code_87) {
		this.code_87 = code_87;
	}

	public int getCode_88() {
		return code_88;
	}

	public void setCode_88(int code_88) {
		this.code_88 = code_88;
	}

	public int getCode_89() {
		return code_89;
	}

	public void setCode_89(int code_89) {
		this.code_89 = code_89;
	}

	public int getCode_90() {
		return code_90;
	}

	public void setCode_90(int code_90) {
		this.code_90 = code_90;
	}

	public int getCode_91() {
		return code_91;
	}

	public void setCode_91(int code_91) {
		this.code_91 = code_91;
	}

	public int getCode_92() {
		return code_92;
	}

	public void setCode_92(int code_92) {
		this.code_92 = code_92;
	}

	public int getCode_93() {
		return code_93;
	}

	public void setCode_93(int code_93) {
		this.code_93 = code_93;
	}

	public int getCode_94() {
		return code_94;
	}

	public void setCode_94(int code_94) {
		this.code_94 = code_94;
	}

	public int getCode_95() {
		return code_95;
	}

	public void setCode_95(int code_95) {
		this.code_95 = code_95;
	}

	public int getCode_96() {
		return code_96;
	}

	public void setCode_96(int code_96) {
		this.code_96 = code_96;
	}

	public int getCode_97() {
		return code_97;
	}

	public void setCode_97(int code_97) {
		this.code_97 = code_97;
	}

	public int getCode_98() {
		return code_98;
	}

	public void setCode_98(int code_98) {
		this.code_98 = code_98;
	}

	public int getCode_99() {
		return code_99;
	}

	public void setCode_99(int code_99) {
		this.code_99 = code_99;
	}

	public int getCode_100() {
		return code_100;
	}

	public void setCode_100(int code_100) {
		this.code_100 = code_100;
	}

	public int getCode_101() {
		return code_101;
	}

	public void setCode_101(int code_101) {
		this.code_101 = code_101;
	}

	public int getCode_102() {
		return code_102;
	}

	public void setCode_102(int code_102) {
		this.code_102 = code_102;
	}

	public int getCode_103() {
		return code_103;
	}

	public void setCode_103(int code_103) {
		this.code_103 = code_103;
	}

	public int getCode_104() {
		return code_104;
	}

	public void setCode_104(int code_104) {
		this.code_104 = code_104;
	}

	public int getCode_105() {
		return code_105;
	}

	public void setCode_105(int code_105) {
		this.code_105 = code_105;
	}

	public int getCode_106() {
		return code_106;
	}

	public void setCode_106(int code_106) {
		this.code_106 = code_106;
	}

	public int getCode_107() {
		return code_107;
	}

	public void setCode_107(int code_107) {
		this.code_107 = code_107;
	}

	public int getCode_108() {
		return code_108;
	}

	public void setCode_108(int code_108) {
		this.code_108 = code_108;
	}

	public int getCode_109() {
		return code_109;
	}

	public void setCode_109(int code_109) {
		this.code_109 = code_109;
	}

	public int getCode_110() {
		return code_110;
	}

	public void setCode_110(int code_110) {
		this.code_110 = code_110;
	}

	public int getCode_111() {
		return code_111;
	}

	public void setCode_111(int code_111) {
		this.code_111 = code_111;
	}

	public int getCode_112() {
		return code_112;
	}

	public void setCode_112(int code_112) {
		this.code_112 = code_112;
	}

	public int getCode_113() {
		return code_113;
	}

	public void setCode_113(int code_113) {
		this.code_113 = code_113;
	}

	public int getCode_114() {
		return code_114;
	}

	public void setCode_114(int code_114) {
		this.code_114 = code_114;
	}

	public int getCode_115() {
		return code_115;
	}

	public void setCode_115(int code_115) {
		this.code_115 = code_115;
	}

	public int getCode_116() {
		return code_116;
	}

	public void setCode_116(int code_116) {
		this.code_116 = code_116;
	}

	public int getCode_117() {
		return code_117;
	}

	public void setCode_117(int code_117) {
		this.code_117 = code_117;
	}

	public int getCode_118() {
		return code_118;
	}

	public void setCode_118(int code_118) {
		this.code_118 = code_118;
	}

	public int getCode_119() {
		return code_119;
	}

	public void setCode_119(int code_119) {
		this.code_119 = code_119;
	}

	public int getCode_120() {
		return code_120;
	}

	public void setCode_120(int code_120) {
		this.code_120 = code_120;
	}

	public int getCode_121() {
		return code_121;
	}

	public void setCode_121(int code_121) {
		this.code_121 = code_121;
	}

	public int getCode_122() {
		return code_122;
	}

	public void setCode_122(int code_122) {
		this.code_122 = code_122;
	}

	public int getCode_123() {
		return code_123;
	}

	public void setCode_123(int code_123) {
		this.code_123 = code_123;
	}

}
