package com.uca.notice.pojos;

// Generated 2015-6-25 13:42:46 by Hibernate Tools 4.0.0

import java.util.Date;

import org.springframework.web.bind.annotation.RequestParam;

/**
 * UcaNotice generated by hbm2java
 */
public class UcaNotice implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer noticeId;
	private String title;
	private String content;
	private Integer releaseStatus;
	private Integer releaseUserId;
	private Date releaseTime;
	private Integer createUserId;
	private Date createTime;
	private Integer updateUserId;
	private Date updateTime;
	private String fileUrl;
	private String sourceFileName;
	private String fileFormat;
	private String fileSize;
	private Integer releaseObj;
	private String contactUser;
	private String tel;
	private String fax;
	private String email;
	
	private String releaseUserName;
	
	private String releaseOrg;
	private Integer isRead;
	private Integer noticeUserId;

	public UcaNotice() {
	}

	public UcaNotice(String title, String content, Integer releaseStatus,
			Integer releaseUserId, Date releaseTime, Integer createUserId,
			Date createTime, Integer updateUserId, Date updateTime,
			String fileUrl, String sourceFileName, String fileFormat,
			String fileSize, Integer releaseObj, String contactUser,
			String tel, String fax, String email) {
		this.title = title;
		this.content = content;
		this.releaseStatus = releaseStatus;
		this.releaseUserId = releaseUserId;
		this.releaseTime = releaseTime;
		this.createUserId = createUserId;
		this.createTime = createTime;
		this.updateUserId = updateUserId;
		this.updateTime = updateTime;
		this.fileUrl = fileUrl;
		this.sourceFileName = sourceFileName;
		this.fileFormat = fileFormat;
		this.fileSize = fileSize;
		this.releaseObj = releaseObj;
		this.contactUser = contactUser;
		this.tel = tel;
		this.fax = fax;
		this.email = email;
	}

	public Integer getNoticeId() {
		return this.noticeId;
	}

	public void setNoticeId(Integer noticeId) {
		this.noticeId = noticeId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Integer getReleaseStatus() {
		return this.releaseStatus;
	}

	public void setReleaseStatus(Integer releaseStatus) {
		this.releaseStatus = releaseStatus;
	}

	public Integer getReleaseUserId() {
		return this.releaseUserId;
	}

	public void setReleaseUserId(Integer releaseUserId) {
		this.releaseUserId = releaseUserId;
	}

	public Date getReleaseTime() {
		return this.releaseTime;
	}

	public void setReleaseTime(Date releaseTime) {
		this.releaseTime = releaseTime;
	}

	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getUpdateUserId() {
		return this.updateUserId;
	}

	public void setUpdateUserId(Integer updateUserId) {
		this.updateUserId = updateUserId;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getFileUrl() {
		return this.fileUrl;
	}

	public void setFileUrl(String fileUrl) {
		this.fileUrl = fileUrl;
	}

	public String getSourceFileName() {
		return this.sourceFileName;
	}

	public void setSourceFileName(String sourceFileName) {
		this.sourceFileName = sourceFileName;
	}

	public String getFileFormat() {
		return this.fileFormat;
	}

	public void setFileFormat(String fileFormat) {
		this.fileFormat = fileFormat;
	}

	public String getFileSize() {
		return this.fileSize;
	}

	public void setFileSize(String fileSize) {
		this.fileSize = fileSize;
	}

	public String getReleaseUserName() {
		return releaseUserName;
	}

	public void setReleaseUserName(String releaseUserName) {
		this.releaseUserName = releaseUserName;
	}

	public Integer getReleaseObj() {
		return releaseObj;
	}

	public void setReleaseObj(Integer releaseObj) {
		this.releaseObj = releaseObj;
	}

	public String getContactUser() {
		return contactUser;
	}

	public void setContactUser(String contactUser) {
		this.contactUser = contactUser;
	}

	public String getTel() {
		return tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getFax() {
		return fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getReleaseOrg() {
		return releaseOrg;
	}

	public void setReleaseOrg(String releaseOrg) {
		this.releaseOrg = releaseOrg;
	}

	public Integer getIsRead() {
		return isRead;
	}

	public void setIsRead(Integer isRead) {
		this.isRead = isRead;
	}

	public Integer getNoticeUserId() {
		return noticeUserId;
	}

	public void setNoticeUserId(Integer noticeUserId) {
		this.noticeUserId = noticeUserId;
	}

}
