package com.uca.archives.pojos;

// Generated 2015-6-4 16:56:21 by Hibernate Tools 3.4.0.CR1


/**
 * UcaOrderNum generated by hbm2java
 */
public class DocExportTpl implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer doctypeval;
	private String tplfilename;
	private String remark;

	public DocExportTpl() {
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getDoctypeval() {
		return doctypeval;
	}

	public void setDoctypeval(Integer doctypeval) {
		this.doctypeval = doctypeval;
	}

	public String getTplfilename() {
		return tplfilename;
	}

	public void setTplfilename(String tplfilename) {
		this.tplfilename = tplfilename;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
	
}
