package com.uca.archives.pojos;

// Generated 2015-6-4 16:56:21 by Hibernate Tools 3.4.0.CR1


/**
 * UcaOrderNum generated by hbm2java
 */
public class UcaArchivesBorrow implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String num;
	private String person;
	private Integer userId;
	private String createDate;

	public UcaArchivesBorrow() {
	}

	public UcaArchivesBorrow(String num, String person, Integer id,Integer userId,String createDate) {
		this.id = id;
		this.num = num;
		this.person = person;
		this.userId = userId;
		this.createDate = createDate;
	}
	
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNum() {
		return num;
	}

	public void setNum(String num) {
		this.num = num;
	}

	public String getPerson() {
		return person;
	}

	public void setPerson(String person) {
		this.person = person;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getCreateDate() {
		return createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}
	
}
