package com.uca.archives.pojos;

// Generated 2015-6-4 16:56:21 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.uca.apply.pojos.UcaApplyQueryRecord;
import com.uca.arclass.pojos.UcaArchivesClass;
import com.uca.catalog.pojos.UcaArchivesCatalog;

/**
 * UcaArchives generated by hbm2java
 */
public class UcaArchives implements java.io.Serializable {

    /**
	 * 
	 */
    private static final long serialVersionUID = 1L;
    private Integer archivesId;
    private UcaArchivesClass ucaArchivesClass;
    private String archivesNum;
    private String orderNum;
    private String projectName;
    private Integer type;
    private Date uploadTime;
    private Integer uploadUserId;
    private String uploadOrgName;
    private String fileUrl;
    private String sourceFileName;
    private Integer checkStatus;
    private Integer handingPersonId;
    private String instruction;
    private Date checkTime;
    private Integer copyStatus;
    private Integer intoFileStatus;
    private Integer workUserId;
    private Date updateTime;
    private Integer updateUserId;
    private Integer queryStatus;
    private Integer sourceId;
    private Integer renameStatus;
    private Set<UcaArchivesCatalog> ucaArchivesCatalogs = new HashSet<UcaArchivesCatalog>(0);
    private Set<UcaApplyQueryRecord> ucaApplyQueryRecords = new HashSet<UcaApplyQueryRecord>(0);

    private String devOrg;

    private String fileUrlOther;
    private String sourceFileNameOther;
    private String applyTime;

    public String getApplyTime() {
        return applyTime;
    }

    public void setApplyTime(String applyTime) {
        this.applyTime = applyTime;
    }

    public String getFileUrlOther() {
        return fileUrlOther;
    }

    public void setFileUrlOther(String fileUrlOther) {
        this.fileUrlOther = fileUrlOther;
    }

    public String getSourceFileNameOther() {
        return sourceFileNameOther;
    }

    public void setSourceFileNameOther(String sourceFileNameOther) {
        this.sourceFileNameOther = sourceFileNameOther;
    }

    public UcaArchives() {
    }

    public UcaArchives(String orderNum) {
        this.orderNum = orderNum;
    }

    public UcaArchives(Integer archivesId, UcaArchivesClass ucaArchivesClass, String archivesNum, String orderNum,
            String projectName, Integer type, Date uploadTime, Integer uploadUserId, String uploadOrgName,
            String fileUrl, String sourceFileName, Integer checkStatus, Integer handingPersonId, String instruction,
            Date checkTime, Integer copyStatus, Integer intoFileStatus, Integer workUserId, Date updateTime,
            Integer updateUserId, Integer queryStatus, Integer sourceId, Set<UcaArchivesCatalog> ucaArchivesCatalogs,
            Set<UcaApplyQueryRecord> ucaApplyQueryRecords, String devOrg) {
        super();
        this.archivesId = archivesId;
        this.ucaArchivesClass = ucaArchivesClass;
        this.archivesNum = archivesNum;
        this.orderNum = orderNum;
        this.projectName = projectName;
        this.type = type;
        this.uploadTime = uploadTime;
        this.uploadUserId = uploadUserId;
        this.uploadOrgName = uploadOrgName;
        this.fileUrl = fileUrl;
        this.sourceFileName = sourceFileName;
        this.checkStatus = checkStatus;
        this.handingPersonId = handingPersonId;
        this.instruction = instruction;
        this.checkTime = checkTime;
        this.copyStatus = copyStatus;
        this.intoFileStatus = intoFileStatus;
        this.workUserId = workUserId;
        this.updateTime = updateTime;
        this.updateUserId = updateUserId;
        this.queryStatus = queryStatus;
        this.sourceId = sourceId;
        this.ucaArchivesCatalogs = ucaArchivesCatalogs;
        this.ucaApplyQueryRecords = ucaApplyQueryRecords;
        this.devOrg = devOrg;
    }

    public Integer getArchivesId() {
        return this.archivesId;
    }

    public void setArchivesId(Integer archivesId) {
        this.archivesId = archivesId;
    }

    public UcaArchivesClass getUcaArchivesClass() {
        return this.ucaArchivesClass;
    }

    public void setUcaArchivesClass(UcaArchivesClass ucaArchivesClass) {
        this.ucaArchivesClass = ucaArchivesClass;
    }

    public String getOrderNum() {
        return this.orderNum;
    }

    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum;
    }

    public Integer getType() {
        return this.type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Date getUploadTime() {
        return this.uploadTime;
    }

    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    public Integer getUploadUserId() {
        return this.uploadUserId;
    }

    public void setUploadUserId(Integer uploadUserId) {
        this.uploadUserId = uploadUserId;
    }

    public String getUploadOrgName() {
        return this.uploadOrgName;
    }

    public void setUploadOrgName(String uploadOrgName) {
        this.uploadOrgName = uploadOrgName;
    }

    public String getFileUrl() {
        return this.fileUrl;
    }

    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }

    public String getSourceFileName() {
        return this.sourceFileName;
    }

    public void setSourceFileName(String sourceFileName) {
        this.sourceFileName = sourceFileName;
    }

    public Integer getCheckStatus() {
        return this.checkStatus;
    }

    public void setCheckStatus(Integer checkStatus) {
        this.checkStatus = checkStatus;
    }

    public Integer getHandingPersonId() {
        return this.handingPersonId;
    }

    public void setHandingPersonId(Integer handingPersonId) {
        this.handingPersonId = handingPersonId;
    }

    public String getInstruction() {
        return this.instruction;
    }

    public void setInstruction(String instruction) {
        this.instruction = instruction;
    }

    public Date getCheckTime() {
        return this.checkTime;
    }

    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    public Integer getCopyStatus() {
        return this.copyStatus;
    }

    public void setCopyStatus(Integer copyStatus) {
        this.copyStatus = copyStatus;
    }

    public Integer getIntoFileStatus() {
        return intoFileStatus;
    }

    public void setIntoFileStatus(Integer intoFileStatus) {
        this.intoFileStatus = intoFileStatus;
    }

    public Integer getWorkUserId() {
        return this.workUserId;
    }

    public void setWorkUserId(Integer workUserId) {
        this.workUserId = workUserId;
    }

    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getUpdateUserId() {
        return this.updateUserId;
    }

    public void setUpdateUserId(Integer updateUserId) {
        this.updateUserId = updateUserId;
    }

    public Integer getQueryStatus() {
        return this.queryStatus;
    }

    public void setQueryStatus(Integer queryStatus) {
        this.queryStatus = queryStatus;
    }

    public Integer getSourceId() {
        return this.sourceId;
    }

    public void setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
    }

    public Set<UcaArchivesCatalog> getUcaArchivesCatalogs() {
        return this.ucaArchivesCatalogs;
    }

    public void setUcaArchivesCatalogs(Set<UcaArchivesCatalog> ucaArchivesCatalogs) {
        this.ucaArchivesCatalogs = ucaArchivesCatalogs;
    }

    public Set<UcaApplyQueryRecord> getUcaApplyQueryRecords() {
        return this.ucaApplyQueryRecords;
    }

    public void setUcaApplyQueryRecords(Set<UcaApplyQueryRecord> ucaApplyQueryRecords) {
        this.ucaApplyQueryRecords = ucaApplyQueryRecords;
    }

    public String getDevOrg() {
        return devOrg;
    }

    public void setDevOrg(String devOrg) {
        this.devOrg = devOrg;
    }

    public String getArchivesNum() {
        return archivesNum;
    }

    public void setArchivesNum(String archivesNum) {
        this.archivesNum = archivesNum;
    }

    public String getProjectName() {
        return projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public Integer getRenameStatus() {
        return renameStatus;
    }

    public void setRenameStatus(Integer renameStatus) {
        this.renameStatus = renameStatus;
    }
}
