package com.uca.archives.pojos;

// Generated 2015-6-4 16:56:21 by Hibernate Tools 3.4.0.CR1


/**
 * UcaOrderNum generated by hbm2java
 */
public class UcaOrderNum implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idYear;
	private Integer start;
	private Integer end;
	private Integer current;

	public UcaOrderNum() {
	}

	public Integer getIdYear() {
		return idYear;
	}

	public void setIdYear(Integer idYear) {
		this.idYear = idYear;
	}

	public Integer getStart() {
		return start;
	}

	public void setStart(Integer start) {
		this.start = start;
	}

	public Integer getEnd() {
		return end;
	}

	public void setEnd(Integer end) {
		this.end = end;
	}

	public Integer getCurrent() {
		return current;
	}

	public void setCurrent(Integer current) {
		this.current = current;
	}

}
