package com.uca.ucasecurity.pojos;

// Generated 2015-6-4 16:56:21 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UcaDic generated by hbm2java
 */
public class UcaDic implements java.io.Serializable {

	private Integer dicId;
	private String name;
	private String code;
	private String val;
	private Date createTime;
	private Date updateTime;
	private Integer createUserId;
	private Integer updateUserId;

	public UcaDic() {
	}

	public UcaDic(String name, String code, String val, Date createTime,
			Date updateTime, Integer createUserId, Integer updateUserId) {
		this.name = name;
		this.code = code;
		this.val = val;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.createUserId = createUserId;
		this.updateUserId = updateUserId;
	}

	public Integer getDicId() {
		return this.dicId;
	}

	public void setDicId(Integer dicId) {
		this.dicId = dicId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getVal() {
		return this.val;
	}

	public void setVal(String val) {
		this.val = val;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	public Integer getUpdateUserId() {
		return this.updateUserId;
	}

	public void setUpdateUserId(Integer updateUserId) {
		this.updateUserId = updateUserId;
	}

}
