package com.uca.exam.pojos;

// Generated 2015-6-25 13:42:46 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * UcaAnswer generated by hbm2java
 */
public class UcaAnswer implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer answerId;
	private Integer epId;
	private Integer eqId;
	private Integer answerUserId;
	private Date answerTime;
	private String answers;
	private Integer score;
	private Integer readOverId;
	private Date readOverTime;
	private Integer status;
	
	private String epName;
	private String userName;
	private String answerTimeStr;
	private String eqName;
	private Integer eqNumber;

	public String getEpName() {
		return epName;
	}

	public void setEpName(String epName) {
		this.epName = epName;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getAnswerTimeStr() {
		return answerTimeStr;
	}

	public void setAnswerTimeStr(String answerTimeStr) {
		this.answerTimeStr = answerTimeStr;
	}

	public String getEqName() {
		return eqName;
	}

	public void setEqName(String eqName) {
		this.eqName = eqName;
	}

	public Integer getEqNumber() {
		return eqNumber;
	}

	public void setEqNumber(Integer eqNumber) {
		this.eqNumber = eqNumber;
	}

	public UcaAnswer() {
	}

	public UcaAnswer(Integer epId, Integer eqId, Integer answerUserId,
			Date answerTime, String answers, Integer score, Integer readOverId,
			Date readOverTime, Integer status) {
		this.epId = epId;
		this.eqId = eqId;
		this.answerUserId = answerUserId;
		this.answerTime = answerTime;
		this.answers = answers;
		this.score = score;
		this.readOverId = readOverId;
		this.readOverTime = readOverTime;
		this.status = status;
	}

	public Integer getAnswerId() {
		return this.answerId;
	}

	public void setAnswerId(Integer answerId) {
		this.answerId = answerId;
	}

	public Integer getEpId() {
		return this.epId;
	}

	public void setEpId(Integer epId) {
		this.epId = epId;
	}

	public Integer getEqId() {
		return this.eqId;
	}

	public void setEqId(Integer eqId) {
		this.eqId = eqId;
	}

	public Integer getAnswerUserId() {
		return this.answerUserId;
	}

	public void setAnswerUserId(Integer answerUserId) {
		this.answerUserId = answerUserId;
	}

	public Date getAnswerTime() {
		return this.answerTime;
	}

	public void setAnswerTime(Date answerTime) {
		this.answerTime = answerTime;
	}

	public String getAnswers() {
		return this.answers;
	}

	public void setAnswers(String answers) {
		this.answers = answers;
	}

	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

	public Integer getReadOverId() {
		return this.readOverId;
	}

	public void setReadOverId(Integer readOverId) {
		this.readOverId = readOverId;
	}

	public Date getReadOverTime() {
		return this.readOverTime;
	}

	public void setReadOverTime(Date readOverTime) {
		this.readOverTime = readOverTime;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
