package com.uca.exam.pojos;

import java.util.Date;

// Generated 2015-6-25 13:42:46 by Hibernate Tools 4.0.0

/**
 * UcaCredit generated by hbm2java
 */
public class UcaCredit implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer creditId;
	private Integer epId;
	private Integer answerUserId;
	private Integer results;
	private Integer credits;
	private Date createTime;
	
	private String epName;
	private String userName;

	public String getEpName() {
		return epName;
	}

	public void setEpName(String epName) {
		this.epName = epName;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public UcaCredit() {
	}

	public UcaCredit(Integer epId, Integer answerUserId, Integer results,
			Integer credits, Date createTime) {
		this.epId = epId;
		this.answerUserId = answerUserId;
		this.results = results;
		this.credits = credits;
		this.createTime = createTime;
	}

	public Integer getCreditId() {
		return this.creditId;
	}

	public void setCreditId(Integer creditId) {
		this.creditId = creditId;
	}

	public Integer getEpId() {
		return this.epId;
	}

	public void setEpId(Integer epId) {
		this.epId = epId;
	}

	public Integer getAnswerUserId() {
		return this.answerUserId;
	}

	public void setAnswerUserId(Integer answerUserId) {
		this.answerUserId = answerUserId;
	}

	public Integer getResults() {
		return this.results;
	}

	public void setResults(Integer results) {
		this.results = results;
	}

	public Integer getCredits() {
		return this.credits;
	}

	public void setCredits(Integer credits) {
		this.credits = credits;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
