package com.uca.exam.pojos;

// Generated 2015-6-25 13:42:46 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.uca.exam.vo.UcaExamQuestionVo;

/**
 * UcaExaminationPaper generated by hbm2java
 */
public class UcaExaminationPaper implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer epId;
	private String epName;
	private Integer examTime;
	private Integer status;
	private Integer passScore;
	private Integer period;
	private Integer createUserId;
	private Date createTime;
	private Integer updateUserId;
	private Date updateTime;
	private Set<UcaExaminationQuestion> ucaExaminationQuestions = new HashSet<UcaExaminationQuestion>(
			0);
	private List<UcaExamQuestionVo> ucaExamQuestionVos;

	public UcaExaminationPaper() {
	}

	public UcaExaminationPaper(String epName, Integer examTime, Integer status,
			Integer passScore, Integer period, Integer createUserId,
			Date createTime, Integer updateUserId, Date updateTime,
			Set<UcaExaminationQuestion> ucaExaminationQuestions) {
		this.epName = epName;
		this.examTime = examTime;
		this.status = status;
		this.passScore = passScore;
		this.period = period;
		this.createUserId = createUserId;
		this.createTime = createTime;
		this.updateUserId = updateUserId;
		this.updateTime = updateTime;
		this.ucaExaminationQuestions = ucaExaminationQuestions;
	}

	public Integer getEpId() {
		return this.epId;
	}

	public void setEpId(Integer epId) {
		this.epId = epId;
	}

	public String getEpName() {
		return this.epName;
	}

	public void setEpName(String epName) {
		this.epName = epName;
	}

	public Integer getExamTime() {
		return this.examTime;
	}

	public void setExamTime(Integer examTime) {
		this.examTime = examTime;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getPassScore() {
		return this.passScore;
	}

	public void setPassScore(Integer passScore) {
		this.passScore = passScore;
	}

	public Integer getPeriod() {
		return this.period;
	}

	public void setPeriod(Integer period) {
		this.period = period;
	}

	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getUpdateUserId() {
		return this.updateUserId;
	}

	public void setUpdateUserId(Integer updateUserId) {
		this.updateUserId = updateUserId;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Set<UcaExaminationQuestion> getUcaExaminationQuestions() {
		return this.ucaExaminationQuestions;
	}

	public void setUcaExaminationQuestions(
			Set<UcaExaminationQuestion> ucaExaminationQuestions) {
		this.ucaExaminationQuestions = ucaExaminationQuestions;
	}

	public List<UcaExamQuestionVo> getUcaExamQuestionVos() {
		return ucaExamQuestionVos;
	}

	public void setUcaExamQuestionVos(List<UcaExamQuestionVo> ucaExamQuestionVos) {
		this.ucaExamQuestionVos = ucaExamQuestionVos;
	}

}
