package com.uca.exam.pojos;

// Generated 2015-6-25 13:42:46 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * UcaExaminationQuestion generated by hbm2java
 */
public class UcaExaminationQuestion implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer eqId;
	private Integer eqNumber;
	private UcaExaminationPaper ucaExaminationPaper;
	private UcaQuestion ucaQuestion;
	private UcaExamQuestionClassify ucaExamQuestionClassify;
	private Integer type;
	private String name;
	private String options;
	private String answer;
	private Integer score;
	private Integer createUserId;
	private Date createTime;
	private Integer updateUserId;
	private Date updateTime;
	
	private Integer epId;
	private Integer questionId;
	private Integer classifyId;
	private String classifyName;

	public Integer getEpId() {
		return epId;
	}

	public void setEpId(Integer epId) {
		this.epId = epId;
	}

	public Integer getQuestionId() {
		return questionId;
	}

	public void setQuestionId(Integer questionId) {
		this.questionId = questionId;
	}

	public UcaExaminationQuestion() {
	}

	public UcaExaminationQuestion(Integer eqNumber, UcaExaminationPaper ucaExaminationPaper,
			UcaQuestion ucaQuestion, Integer type, String name, String options,
			String answer, Integer score, Integer createUserId,
			Date createTime, Integer updateUserId, Date updateTime) {
		this.eqNumber = eqNumber;
		this.ucaExaminationPaper = ucaExaminationPaper;
		this.ucaQuestion = ucaQuestion;
		this.type = type;
		this.name = name;
		this.options = options;
		this.answer = answer;
		this.score = score;
		this.createUserId = createUserId;
		this.createTime = createTime;
		this.updateUserId = updateUserId;
		this.updateTime = updateTime;
	}

	public Integer getEqId() {
		return this.eqId;
	}

	public void setEqId(Integer eqId) {
		this.eqId = eqId;
	}

	public Integer getEqNumber() {
		return eqNumber;
	}

	public void setEqNumber(Integer eqNumber) {
		this.eqNumber = eqNumber;
	}

	public UcaExaminationPaper getUcaExaminationPaper() {
		return this.ucaExaminationPaper;
	}

	public void setUcaExaminationPaper(UcaExaminationPaper ucaExaminationPaper) {
		this.ucaExaminationPaper = ucaExaminationPaper;
	}

	public UcaQuestion getUcaQuestion() {
		return this.ucaQuestion;
	}

	public void setUcaQuestion(UcaQuestion ucaQuestion) {
		this.ucaQuestion = ucaQuestion;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getOptions() {
		return this.options;
	}

	public void setOptions(String options) {
		this.options = options;
	}

	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getUpdateUserId() {
		return this.updateUserId;
	}

	public void setUpdateUserId(Integer updateUserId) {
		this.updateUserId = updateUserId;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public UcaExamQuestionClassify getUcaExamQuestionClassify() {
		return ucaExamQuestionClassify;
	}

	public void setUcaExamQuestionClassify(
			UcaExamQuestionClassify ucaExamQuestionClassify) {
		this.ucaExamQuestionClassify = ucaExamQuestionClassify;
	}

	public Integer getClassifyId() {
		return classifyId;
	}

	public void setClassifyId(Integer classifyId) {
		this.classifyId = classifyId;
	}

	public String getClassifyName() {
		return classifyName;
	}

	public void setClassifyName(String classifyName) {
		this.classifyName = classifyName;
	}

}
