package com.uca.exam.pojos;

// Generated 2015-6-25 13:42:46 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UcaQuestion generated by hbm2java
 */
public class UcaQuestion implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer questionId;
	private UcaExamQuestionClassify ucaExamQuestionClassify;
	private Integer type;
	private String name;
	private String options;
	private String answer;
	private Integer createUserId;
	private Date createTime;
	private Integer updateUserId;
	private Date updateTime;
	private Set<UcaExaminationQuestion> ucaExaminationQuestions = new HashSet<UcaExaminationQuestion>(
			0);
	
	private Integer classifyId;
	private String classifyName;

	public UcaQuestion() {
	}

	public UcaQuestion(Integer type, String name, String options, String answer,
			Integer createUserId, Date createTime, Integer updateUserId,
			Date updateTime, Set<UcaExaminationQuestion> ucaExaminationQuestions) {
		this.type = type;
		this.name = name;
		this.options = options;
		this.answer = answer;
		this.createUserId = createUserId;
		this.createTime = createTime;
		this.updateUserId = updateUserId;
		this.updateTime = updateTime;
		this.ucaExaminationQuestions = ucaExaminationQuestions;
	}

	public Integer getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Integer questionId) {
		this.questionId = questionId;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getOptions() {
		return this.options;
	}

	public void setOptions(String options) {
		this.options = options;
	}

	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getUpdateUserId() {
		return this.updateUserId;
	}

	public void setUpdateUserId(Integer updateUserId) {
		this.updateUserId = updateUserId;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Set<UcaExaminationQuestion> getUcaExaminationQuestions() {
		return this.ucaExaminationQuestions;
	}

	public void setUcaExaminationQuestions(
			Set<UcaExaminationQuestion> ucaExaminationQuestions) {
		this.ucaExaminationQuestions = ucaExaminationQuestions;
	}

	public UcaExamQuestionClassify getUcaExamQuestionClassify() {
		return ucaExamQuestionClassify;
	}

	public void setUcaExamQuestionClassify(
			UcaExamQuestionClassify ucaExamQuestionClassify) {
		this.ucaExamQuestionClassify = ucaExamQuestionClassify;
	}

	public Integer getClassifyId() {
		return classifyId;
	}

	public void setClassifyId(Integer classifyId) {
		this.classifyId = classifyId;
	}

	public String getClassifyName() {
		return classifyName;
	}

	public void setClassifyName(String classifyName) {
		this.classifyName = classifyName;
	}

}
