package com.uca.apply.pojos;

// Generated 2015-6-4 16:56:21 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Transient;

import com.uca.archives.pojos.UcaArchives;

/**
 * UcaApplyQueryRecord generated by hbm2java
 */
public class UcaApplyQueryRecord implements java.io.Serializable {

    /**
	 * 
	 */
    private static final long serialVersionUID = 1L;
    private Integer aqId;
    private UcaArchives ucaArchives;
    private Date applyTime;
    private Integer checkStatus;
    private String instruction;
    private Integer checkUserId;
    private Date checkTime;
    private Date appointmentTime;

    @Transient
    private Integer archivesId;
    @Transient
    private String orderNum;
    @Transient
    private String projectName;

    public UcaApplyQueryRecord() {
    }

    public UcaApplyQueryRecord(UcaArchives ucaArchives, Date applyTime, Integer checkStatus, String instruction,
            Integer checkUserId, Date checkTime) {
        this.ucaArchives = ucaArchives;
        this.applyTime = applyTime;
        this.checkStatus = checkStatus;
        this.instruction = instruction;
        this.checkUserId = checkUserId;
        this.checkTime = checkTime;
    }

    public Integer getAqId() {
        return this.aqId;
    }

    public void setAqId(Integer aqId) {
        this.aqId = aqId;
    }

    public UcaArchives getUcaArchives() {
        return this.ucaArchives;
    }

    public void setUcaArchives(UcaArchives ucaArchives) {
        this.ucaArchives = ucaArchives;
    }

    public Date getApplyTime() {
        return this.applyTime;
    }

    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    public Integer getCheckStatus() {
        return this.checkStatus;
    }

    public void setCheckStatus(Integer checkStatus) {
        this.checkStatus = checkStatus;
    }

    public String getInstruction() {
        return this.instruction;
    }

    public void setInstruction(String instruction) {
        this.instruction = instruction;
    }

    public Integer getCheckUserId() {
        return this.checkUserId;
    }

    public void setCheckUserId(Integer checkUserId) {
        this.checkUserId = checkUserId;
    }

    public Date getCheckTime() {
        return this.checkTime;
    }

    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    public Integer getArchivesId() {
        return archivesId;
    }

    public void setArchivesId(Integer archivesId) {
        this.archivesId = archivesId;
    }

    public String getOrderNum() {
        return orderNum;
    }

    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum;
    }

    public String getProjectName() {
        return projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public Date getAppointmentTime() {
        return appointmentTime;
    }

    public void setAppointmentTime(Date appointmentTime) {
        this.appointmentTime = appointmentTime;
    }

}
