package com.uca.apply.pojos;

import java.util.Date;

import javax.persistence.Transient;

// Generated 2015-6-4 16:56:21 by Hibernate Tools 3.4.0.CR1

/**
 * UcaAuditWorkStatistics generated by hbm2java
 */
public class UcaAuditWorkStatistics implements java.io.Serializable {

    /**
	 * 
	 */
    private static final long serialVersionUID = 1L;
    private Integer workId;
    private Integer userId;
    private String projectName;
    private Integer picNum;
    private Double picSize;
    private Integer movMinute;
    private Double movSize;
    private Date createTime;

    @Transient
    private String userName;

    public UcaAuditWorkStatistics() {
    }

    public Integer getWorkId() {
        return workId;
    }

    public void setWorkId(Integer workId) {
        this.workId = workId;
    }

    public String getProjectName() {
        return projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getPicNum() {
        return picNum;
    }

    public void setPicNum(Integer picNum) {
        this.picNum = picNum;
    }

    public Double getPicSize() {
        return picSize;
    }

    public void setPicSize(Double picSize) {
        this.picSize = picSize;
    }

    public Integer getMovMinute() {
        return movMinute;
    }

    public void setMovMinute(Integer movMinute) {
        this.movMinute = movMinute;
    }

    public Double getMovSize() {
        return movSize;
    }

    public void setMovSize(Double movSize) {
        this.movSize = movSize;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

}
