package com.uca.survey.pojos;

// Generated 2015-6-25 13:42:46 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * UcaSurveyOption generated by hbm2java
 */
public class UcaSurveyOption implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private UcaSurvey ucaSurvey;
	private String options;
	private Integer createUserId;
	private Date createTime;
	private Integer updateUserId;
	private Date updateTime;
	
	private Integer surveyId;
	private Integer count;

	public UcaSurveyOption() {
	}

	public UcaSurveyOption(UcaSurvey ucaSurvey, String options, Integer createUserId,
			Date createTime, Integer updateUserId, Date updateTime) {
		this.ucaSurvey = ucaSurvey;
		this.options = options;
		this.createUserId = createUserId;
		this.createTime = createTime;
		this.updateUserId = updateUserId;
		this.updateTime = updateTime;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public UcaSurvey getUcaSurvey() {
		return ucaSurvey;
	}

	public void setUcaSurvey(UcaSurvey ucaSurvey) {
		this.ucaSurvey = ucaSurvey;
	}

	public String getOptions() {
		return options;
	}

	public void setOptions(String options) {
		this.options = options;
	}

	public Integer getCreateUserId() {
		return createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getUpdateUserId() {
		return updateUserId;
	}

	public void setUpdateUserId(Integer updateUserId) {
		this.updateUserId = updateUserId;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Integer getSurveyId() {
		return surveyId;
	}

	public void setSurveyId(Integer surveyId) {
		this.surveyId = surveyId;
	}

	public Integer getCount() {
		return count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

}
