package com.uca.survey.pojos;

// Generated 2015-6-25 13:42:46 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * UcaSurveyResult generated by hbm2java
 */
public class UcaSurveyResult implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private UcaSurvey ucaSurvey;
	private String result;
	private Integer resultUserId;
	private Date resultTime;
	
	private Integer surveyId;
	private String userName;
	private String resultTimeStr;

	public UcaSurveyResult() {
	}

	public UcaSurveyResult(UcaSurvey ucaSurvey, String result, 
			Integer resultUserId, Date resultTime, Integer updateUserId, Date updateTime) {
		this.ucaSurvey = ucaSurvey;
		this.result = result;
		this.resultUserId = resultUserId;
		this.resultTime = resultTime;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public UcaSurvey getUcaSurvey() {
		return ucaSurvey;
	}

	public void setUcaSurvey(UcaSurvey ucaSurvey) {
		this.ucaSurvey = ucaSurvey;
	}

	public String getResult() {
		return result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public Integer getResultUserId() {
		return resultUserId;
	}

	public void setResultUserId(Integer resultUserId) {
		this.resultUserId = resultUserId;
	}

	public Date getResultTime() {
		return resultTime;
	}

	public void setResultTime(Date resultTime) {
		this.resultTime = resultTime;
	}

	public Integer getSurveyId() {
		return surveyId;
	}

	public void setSurveyId(Integer surveyId) {
		this.surveyId = surveyId;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getResultTimeStr() {
		return resultTimeStr;
	}

	public void setResultTimeStr(String resultTimeStr) {
		this.resultTimeStr = resultTimeStr;
	}

}
