package com.uca.meeting.pojos;

// Generated 2015-6-25 13:42:46 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UcaMrApply generated by hbm2java
 */
public class UcaMrApply implements java.io.Serializable {
    /**
	 * 
	 */
    private static final long serialVersionUID = 1L;
    private Integer applyId;
    private Integer mrId;
    private String conferenceName;
    private String participants;
    private Date meetingBeginTime;
    private Date meetingEndTime;
    private String remark;
    private Integer applyUserId;
    private Date applyTime;
    private String devices;

    private Integer flag;
    private String vleStr;
    private String meetingName;

    private String applyDate;
    private String applyName;
    private String applyOrg;
    private String beginDate;
    private String endDate;

    private Set<UcaMrApplyUser> ucaMrApplyUser = new HashSet<UcaMrApplyUser>(0);

    public UcaMrApply() {
    }

    public UcaMrApply(Integer applyId, Integer mrId, String conferenceName, Date meetingBeginTime, Date meetingEndTime,
            String remark, Integer applyUserId, Date applyTime, Set<UcaMrApplyUser> ucaMrApplyUser) {
        super();
        this.applyId = applyId;
        this.mrId = mrId;
        this.conferenceName = conferenceName;
        this.meetingBeginTime = meetingBeginTime;
        this.meetingEndTime = meetingEndTime;
        this.remark = remark;
        this.applyUserId = applyUserId;
        this.applyTime = applyTime;
        this.ucaMrApplyUser = ucaMrApplyUser;
    }

    public Integer getApplyId() {
        return this.applyId;
    }

    public void setApplyId(Integer applyId) {
        this.applyId = applyId;
    }

    public Integer getMrId() {
        return this.mrId;
    }

    public void setMrId(Integer mrId) {
        this.mrId = mrId;
    }

    public String getConferenceName() {
        return this.conferenceName;
    }

    public void setConferenceName(String conferenceName) {
        this.conferenceName = conferenceName;
    }

    public String getParticipants() {
        return this.participants;
    }

    public void setParticipants(String participants) {
        this.participants = participants;
    }

    public Date getMeetingBeginTime() {
        return meetingBeginTime;
    }

    public void setMeetingBeginTime(Date meetingBeginTime) {
        this.meetingBeginTime = meetingBeginTime;
    }

    public Date getMeetingEndTime() {
        return meetingEndTime;
    }

    public void setMeetingEndTime(Date meetingEndTime) {
        this.meetingEndTime = meetingEndTime;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Integer getApplyUserId() {
        return this.applyUserId;
    }

    public void setApplyUserId(Integer applyUserId) {
        this.applyUserId = applyUserId;
    }

    public Date getApplyTime() {
        return this.applyTime;
    }

    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    public Integer getFlag() {
        return flag;
    }

    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    public String getVleStr() {
        return vleStr;
    }

    public void setVleStr(String vleStr) {
        this.vleStr = vleStr;
    }

    public Set<UcaMrApplyUser> getUcaMrApplyUser() {
        return ucaMrApplyUser;
    }

    public void setUcaMrApplyUser(Set<UcaMrApplyUser> ucaMrApplyUser) {
        this.ucaMrApplyUser = ucaMrApplyUser;
    }

    public String getMeetingName() {
        return meetingName;
    }

    public void setMeetingName(String meetingName) {
        this.meetingName = meetingName;
    }

    public String getApplyDate() {
        return applyDate;
    }

    public void setApplyDate(String applyDate) {
        this.applyDate = applyDate;
    }
    
    public String getApplyName() {
        return applyName;
    }

    public void setApplyName(String applyName) {
        this.applyName = applyName;
    }

    public String getApplyOrg() {
        return applyOrg;
    }

    public void setApplyOrg(String applyOrg) {
        this.applyOrg = applyOrg;
    }

    public String getBeginDate() {
        return beginDate;
    }

    public void setBeginDate(String beginDate) {
        this.beginDate = beginDate;
    }

    public String getEndDate() {
        return endDate;
    }

    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    public String getDevices() {
        return devices;
    }

    public void setDevices(String devices) {
        this.devices = devices;
    }
}
